#!/bin/sh -efu

. "$TOPDIR/tests/common.sh"

WORKDIR="$1"

prepare

cat > "$WORKDIR/syslog.conf" <<EOF
log_format: %t %h %m
*.*     $WORKDIR/output/messages.log
*.info  $WORKDIR/syslog-mark.log
EOF

run_syslogd &
sleep 0.3

i=0
while [ $i -lt 100 ]; do
	logger --socket "$WORKDIR/log" -p "local0.info" --id="1" --tag "USER" "TEST"
	i=$(($i+1))
done

wait_mark
normilize_logs "$WORKDIR/output"

diff -rU0 "$WORKDIR/expect" "$WORKDIR/output"
