#!/bin/sh -efu

. "$TOPDIR/tests/common.sh"

WORKDIR="$1"

prepare

cat > "$WORKDIR/syslog.conf" <<EOF
local0.*;local0.!=info  $WORKDIR/output/local0-no-info.log
local1.*;local1.!err    $WORKDIR/output/local1-less-err.log
*.info                  $WORKDIR/syslog-mark.log
EOF

run_syslogd &
sleep 3

for f in $facilities; do
	for p in $priorities; do
		logger \
			--socket "$WORKDIR/log" \
			--socket-errors=on \
			-p "$f.$p" "TEST $f.$p"
	done
done

wait_mark
normilize_logs "$WORKDIR/output"

diff -rU0 "$WORKDIR/expect" "$WORKDIR/output"
