dist: focal
addons:
  apt:
    update: true
    packages: [ gcc, clang, musl, musl-dev, musl-tools, util-linux, iproute2, autoconf, automake, make ]
language: c
branches:
  only:
  - master
  - travis
matrix:
  include:
    - name: "amd64 / gcc / glibc / dynamic"
      arch: amd64
      os: linux
      env:
         - CC="gcc"
    - name: "amd64 / clang / libclang / dynamic"
      arch: amd64
      os: linux
      env:
         - CC="clang"
    - name: "amd64 / musl-gcc / musl / static"
      arch: amd64
      os: linux
      env:
         # https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
         #  -idirafter /usr/include/                  # Needed for Travis/Ubuntu build to pass, for linux/kd.h, etc.
         #  -idirafter /usr/include/x86_64-linux-gnu/ # Needed for Travis/Ubuntu build to pass, for asm/types.h
         - CC="musl-gcc -static -idirafter /usr/include/ -idirafter /usr/include/x86_64-linux-gnu/"
script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
