#!/bin/sh -efu

if ! file "$top_builddir/src/syslogd/syslogd" | grep -qs 'statically linked'; then
	exit 77
fi

if [ -z "${UNSHARE-}" ]; then
	export UNSHARE=1
	exec unshare --pid --user --uts --fork --map-root-user --mount-proc "$0"
fi

name="${0##*/check-}"

. "$srcdir/common.sh"

WORKDIR="$builddir/_build/$name"

prepare "$WORKDIR"

{
	printf 'log_format: %s\n' "%t %h %m"
	for p in $priorities; do
		printf '*.%s\t%s\n' "$p" "$WORKDIR/output/syslog-$p.log"
	done
	printf '*.info\t%s\n' "$WORKDIR/syslog-mark.log"
} > "$WORKDIR/syslog.conf"

SYSLOGD_WRAPPER="$srcdir/rlimit-prog.sh -v 3000 --" \
run_syslogd

for f in $facilities; do
	for p in $priorities; do
		logger \
			--socket "$WORKDIR/log" \
			--socket-errors=on \
			-p "$f.$p" "TEST $f.$p"
	done
done

wait_mark
normilize_logs "$WORKDIR/output"

diff -rU0 "$srcdir/data/$name/expect" "$WORKDIR/output"
