#!/bin/sh -efu

if [ -z "${UNSHARE-}" ]; then
	export UNSHARE=1
	exec unshare --pid --user --fork --map-root-user --mount-proc "$0"
fi

name="${0##*/check-}"

. "$srcdir/common.sh"

WORKDIR="$builddir/_build/$name"

prepare "$WORKDIR"

cat > "$WORKDIR/syslog.conf" <<EOF
log_format: %t %h %m
*.*     $WORKDIR/output/messages.log
*.info  $WORKDIR/syslog-mark.log
EOF

run_syslogd

i=0
while [ $i -lt 100 ]; do
	logger --socket "$WORKDIR/log" -p "local0.info" --id="1" --tag "USER" "TEST"
	i=$(($i+1))
done

wait_mark
normilize_logs "$WORKDIR/output"

diff -rU0 "$srcdir/data/$name/expect" "$WORKDIR/output"
