#!/bin/sh -efu

if [ -z "${UNSHARE-}" ]; then
	export UNSHARE=1
	exec unshare --pid --user --uts --fork --map-root-user --mount-proc "$0"
fi

name="${0##*/check-}"

. "$srcdir/common.sh"

WORKDIR="$builddir/_build/$name"

prepare "$WORKDIR"

cat > "$WORKDIR/syslog.conf" <<EOF
log_format: %t %h %m
*.*     $WORKDIR/output/messages.log
*.info  $WORKDIR/syslog-mark.log
EOF

run_syslogd

i=0
while [ $i -lt 10 ]; do
	{
		n=0
		while [ $n -lt 100 ]; do
			printf '%s' "0123456789 "
			n=$(($n + 1))
		done
	} |
		logger --socket "$WORKDIR/log" -p "local0.info" --tag "root"
	i=$(($i+1))
done

wait_mark
normilize_logs "$WORKDIR/output"

diff -rU0 "$srcdir/data/$name/expect" "$WORKDIR/output"
