#!/bin/sh -efu

if [ -z "${UNSHARE-}" ]; then
	export UNSHARE=1
	exec unshare --pid --user --uts --fork --map-root-user --mount-proc "$0"
fi

name="${0##*/check-}"

. "$srcdir/common.sh"

WORKDIR="$builddir/_build/$name"

prepare "$WORKDIR"

cat > "$WORKDIR/syslog.conf" <<EOF
log_format: %t %h %m
*.=CRIT;local0.none     $WORKDIR/output/critical.log
*.=crit                 $WORKDIR/output/critical-all.log
LoCaL0.*;local0.!=info  $WORKDIR/output/local0.log
*.iNFo                  $WORKDIR/syslog-mark.log
EOF

run_syslogd

for f in $facilities; do
	for p in $priorities; do
		logger -i \
			--socket "$WORKDIR/log" \
			--socket-errors=on \
			-p "$f.$p" "TEST $f.$p"
	done
done

wait_mark
normilize_logs "$WORKDIR/output"

diff -rU0 "$srcdir/data/$name/expect" "$WORKDIR/output"
