#!/bin/sh -efu

[ -n "${TRAVIS_COMPILER-}" ] ||
	exit 0

testcase="$1"; shift

[ ! -d "$TOPDIR/tests/$testcase/.travis.cmd" ] ||
	exit 0

mkdir -p -- "$TOPDIR/tests/$testcase/.travis.cmd"

printf '%s\n' "$1" > "$TOPDIR/tests/$testcase/.travis.cmd/msg"
date +'%s%N'       > "$TOPDIR/tests/$testcase/.travis.cmd/ts"

printf 'travis_fold:start:%s\r' "$1"
printf 'travis_time:start:ts.%s\r' "$1"
printf '\n'
