#!/bin/sh -efu

[ -n "${TRAVIS_COMPILER-}" ] ||
	exit 0

testcase="$1"; shift

[ -d "$TOPDIR/tests/$testcase/.travis.cmd" ] ||
	exit 0

read -r msg < "$TOPDIR/tests/$testcase/.travis.cmd/msg" ||:
read -r ts  < "$TOPDIR/tests/$testcase/.travis.cmd/ts"  ||:

te="$(date +'%s%N')"
duration="$((${te:-0} - ${ts:-0}))"

printf 'travis_time:end:ts.%s:start=%s,finish=%s,duration=%s\r' "$msg" "$ts" "$te" "$duration"
printf 'travis_fold:end:%s\r' "$msg"
printf '\n'

rm -rf -- "$TOPDIR/tests/$testcase/.travis.cmd"
