name: CI
on:
  push:
    branches:
      - master
      - for-master
    tags:
      - v*
jobs:
  ubuntu_gcc_glibc_dynamic:
    name: Tests on ubuntu (gcc / glibc / dynamic)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake make
        sudo apt-get install -y gcc
        sudo apt-get install -y util-linux iproute2 socat file valgrind python3-pip python3-venv
    - name: configure
      run: |
        ./autogen.sh
        env CC=gcc ./configure
    - name: build
      run: |
        make V=1

  ubuntu_clang_glibc_dynamic:
    name: Tests on ubuntu (clang / glibc / dynamic)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake make
        sudo apt-get install -y clang
        sudo apt-get install -y util-linux iproute2 socat file valgrind python3-pip python3-venv
    - name: configure
      run: |
        ./autogen.sh
        env CC=clang ./configure
    - name: build
      run: |
        make V=1

  ubuntu_gcc_glibc_static:
    name: Tests on ubuntu (gcc / glibc / static)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake make
        sudo apt-get install -y gcc
        sudo apt-get install -y util-linux iproute2 socat file valgrind
    - name: configure
      run: |
        ./autogen.sh
        env CC=gcc ./configure
    - name: build
      run: |
        make V=1 LDFLAGS=-static

  ubuntu_gcc_musl_static:
    name: Tests on ubuntu (musl-gcc / musl / dynamic)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake make
        sudo apt-get install -y musl musl-dev musl-tools
        sudo apt-get install -y util-linux iproute2 socat file valgrind
    - name: configure
      run: |
        ./autogen.sh
        ./configure --host=x86_64-linux-musl
    - name: build
      run: |
        make V=1 CFLAGS+="-idirafter /usr/include/ -idirafter /usr/include/x86_64-linux-gnu/"
